name: Release

on:
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    runs-on:
      - ubuntu-24.04
    steps:
      - name: Checkout repo
        # v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test and Package
        env:
          GUARDIAN_MYSQL_USER: user
          GUARDIAN_MYSQL_PASSWORD: password
          GUARDIAN_MYSQL_DATABASE: guardian
          GUARDIAN_REDIS_PORT: 6379
        run: mvn clean verify -Dlogback.configurationFile=logback/logback-development.xml

      - name: Upload Artefact
        # v2.2.1
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: |
            target/guardian/guardian.jar
            src/main/resources/logback/logback.xml
